name: 'Upload to OBS'
description: 'Upload to OBS'
author: 'Elysia'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  remove-old-sources:
    description: 'Remove old sources from OBS package'
    required: true
    default: true
  obs-package-name:
    description: 'OBS package name'
    required: true
  obs-project-name:
    description: 'OBS project name'
    required: true
  obs-user-name:
    description: 'OBS user name'
    required: true
  obs-password:
    description: 'OBS password'
    required: true
  obs-instance-url:
    description: 'OBS instance URL'
    required: true
    default: 'https://api.opensuse.org'
  local-package-dir:
    description: 'Local package directory'
    required: true

runs:
  using: node20
  main: dist/index.js
